name: 'Setup vcpkg for Android'
description: 'Setup vcpkg for Android workflow'
inputs:
  vcpkg-path:
    description: 'Path to vcpkg'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set VCPKG_ROOT
      shell: bash
      run: echo "VCPKG_ROOT=${{ github.workspace }}/${{ inputs.vcpkg-path }}" >> $GITHUB_ENV

    - name: Bootstrap vcpkg
      shell: bash
      run: ./bootstrap-vcpkg.sh -disableMetrics
      working-directory: ${{ inputs.vcpkg-path }}
      
