macro(enable_lto COMPILER_KIND)
    if (${COMPILER_KIND} STREQUAL MSVC)
    elseif (${COMPILER_KIND} STREQUAL APPLE)
        string(APPEND VCPKG_C_FLAGS " -ffunction-sections -fdata-sections")
        string(APPEND VCPKG_CXX_FLAGS " -ffunction-sections -fdata-sections")
        string(APPEND VCPKG_LINKER_FLAGS " -Wl,-dead_strip")
    elseif (${COMPILER_KIND} STREQUAL "GNU")
        string(APPEND VCPKG_C_FLAGS " -ffunction-sections -fdata-sections")
        string(APPEND VCPKG_CXX_FLAGS " -ffunction-sections -fdata-sections")
        string(APPEND VCPKG_LINKER_FLAGS " -Wl,--gc-sections")
    elseif (${COMPILER_KIND} STREQUAL "Clang")
        string(APPEND VCPKG_C_FLAGS " -ffunction-sections -fdata-sections")
        string(APPEND VCPKG_CXX_FLAGS " -ffunction-sections -fdata-sections")
        string(APPEND VCPKG_LINKER_FLAGS " -Wl,--gc-sections")
    endif ()
endmacro()
