name: 'CMake build for libnakama'
description: 'Configures build environment and invokes CMake. Not generic, tailored for libnakama.'
inputs:
  preset:
    description: 'Configure preset name'
    required: true
  build_type:
    description: 'Build config: MinSizeRel or Debug'
    required: true
    default: 'MinSizeRel'
  artifact_retention_days:
    description: 'Artifact retention days'
    default: "2"
  GITHUB_TOKEN:
    description: 'Github token for Github Package Registry'
    required: true
outputs:
  artifact_name:
    description: 'Artifact name'
    value: ${{ steps.artifact_name.outputs.name }}
runs:
  using: "composite"
  steps:
    - run: |
        rm -rf out
        cmake --preset ${{ inputs.preset }} ${{ steps.cmake_args.outputs.args }}
        cmake --build ./build/${{ inputs.preset }} --config ${{ inputs.build_type }} --verbose
        cmake --install ./build/${{ inputs.preset }} --config ${{ inputs.build_type }}
        cd test && cmake --preset ${{ inputs.preset }}
        cd test && cmake --build ./build/${{ inputs.preset }} --config ${{ inputs.build_type }} --verbose
        cd test && cmake --install ./build/${{ inputs.preset }} --config ${{ inputs.build_type }}
        sha=${{ github.sha }}
        preset="${{ inputs.preset }}"
        # strip -host_{arm64,x64} from the preset, because it is not relevant for users
        preset=${preset%-host_*}
        name="libnakama-${preset}-${{ inputs.build_type }}-git.${sha:0:8}"
        echo "::set-output name=artifact::${name}"
        bin7z=$(type -p 7z || type -p 7zr)  # windows and linux/osx has different 7z binaries names
        cd out
        ${bin7z} a ../${{ steps.artifact_name.outputs.artifact }}.7z '*'
      shell: bash
      working-directory: "${GITHUB_WORKSPACE}/nakama-cpp"
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.artifact_name.outputs.artifact }}
        path: ./${{ steps.artifact_name.outputs.artifact }}.7z
        retention-days: ${{ inputs.artifact_retention_days }}
    - if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.artifact_name.outputs.artifact }}-workdir-debug
        path: |
          ${GITHUB_WORKSPACE}/nakama-cpp/build
          ${GITHUB_WORKSPACE}/vcpkg
        retention-days: 1
