name: 'Handle Failure'
description: 'Handle a build failure'
inputs:
  vcpkg-path:
    description: 'Relative path under $GITHUB_WORKSPACE to the vcpkg repository'
    required: true
  nakama-cpp-path:
    description: 'Relative path under $GITHUB_WORKSPACE to the nakama-cpp repository'
    required: true
runs:
  using: "composite"
  steps:
    - if: runner.os != 'Windows'
      run: |
        cd $GITHUB_WORKSPACE/${{ inputs.nakama-cpp-path }}
        if [ -d "./build" ]; then
          zip -r build ./build
        fi
        if [ -d "./out" ]; then
          zip -r out ./out
        fi
        cd $GITHUB_WORKSPACE/${{ inputs.vcpkg-path }}
        if [ -d "./buildtrees" ]; then
          zip -r buildtrees ./buildtrees
        fi
      shell: bash
    - if: runner.os == 'Windows'
      run: |
        cd $GITHUB_WORKSPACE/${{ inputs.nakama-cpp-path }}
        if (Test-Path -Path './build') {
          Compress-Archive -Path ./build -DestinationPath build.zip
        }
        if (Test-Path -Path './out') {
          Compress-Archive -Path ./out -DestinationPath out.zip
        }
        cd $GITHUB_WORKSPACE/${{ inputs.vcpkg-path }}
        if (Test-Path -Path './buildtrees') {
          Compress-Archive -Path ./buildtrees -DestinationPath buildtrees.zip
        }
      shell: powershell
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.build.outputs.artifact_name }}-workdir-debug
        path: |
          ./${{ inputs.nakama-cpp-path }}/build.zip
          ./${{ inputs.nakama-cpp-path }}/out.zip
          ./${{ inputs.vcpkg-path }}/buildtrees.zip
        retention-days: 1