name: 'Build platform and upload'
description: 'Build for a single platform and upload the resulting artifact.'
inputs:
  preset:
    description: 'Configure preset name'
    required: true
  nakama-cpp-path:
    description: 'Relative path under $GITHUB_WORKSPACE to the nakama-cpp repository'
    required: true
  build_type:
    description: 'Build config: MinSizeRel or Debug'
    required: true
    default: 'MinSizeRel'
runs:
  using: "composite"
  steps:
    - id: build
      run: |
        rm -rf out
        cmake --preset ${{ inputs.preset }}
        cmake --build ./build/${{ inputs.preset }} --config ${{ inputs.build_type }} --verbose
        cmake --install ./build/${{ inputs.preset }} --config ${{ inputs.build_type }}
      working-directory: ${{ inputs.nakama-cpp-path }}
      shell: bash

    - name: Get folder name
      id: get-folder-name
      run: |
        path="./nakama-cpp/out"
        for dir in "$path"/*/; do
          folder_name=$(basename "$dir")
          echo "::set-output name=folder-name::$folder_name"
        done
      shell: bash

    - name: Create zip file
      id: create-zip
      run: |
        folder_name="${{ steps.get-folder-name.outputs.folder-name }}"
        cd "./nakama-cpp/out"
        zip -r "./${folder_name}.zip" "./${folder_name}"
        echo "::set-output name=artifact-path::${PWD}/${folder_name}.zip"
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.get-folder-name.outputs.folder-name }}
        path: ${{ steps.create-zip.outputs.artifact-path }}
