name: 'Build test and run'
description: 'Build a test for nakama-cpp and run it'
inputs:
  preset:
    description: 'Configure preset name'
    required: true
  nakama-cpp-path:
    description: 'Relative path under $GITHUB_WORKSPACE to the nakama-cpp repository'
    required: true
  testrunner-pat:
    description: 'PAT to access the private Nakama testrunner'
    required: true
  native-tool-options:
    description: 'Flags to pass to the underlying build system used by the CMake generator.'
    required: false
runs:
  using: "composite"
  steps:
    - id: build
      run: |
        cmake --preset ${{ inputs.preset }}
        cmake --build ./build/${{ inputs.preset }} --target install -- ${{ inputs.native-tool-options }}
      shell: bash
      working-directory: ${{ inputs.nakama-cpp-path }}/test
    - name: Checkout nakama-client-testrunner
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        repository: heroiclabs/nakama-client-testrunner
        token: ${{ inputs.testrunner-pat }}
    - name: Start docker containers for nakama-client-testrunner
      working-directory: nakama-client-testrunner
      run: ./docker-compose up -d --wait
      shell: bash
    - run: |
        ./${{ inputs.nakama-cpp-path }}/test/out/${{ inputs.preset }}/nakama-test || {
            echo "Test failed, showing Nakama log for diagnostics";
            cat /tmp/nakama.log;
            exit 1;
        }
      shell: bash
