name: 'Build test and run'
description: 'Build a test for nakama-cpp and run it'
inputs:
  preset:
    description: 'Configure preset name'
    required: true
  nakama-cpp-path:
    description: 'Relative path under $GITHUB_WORKSPACE to the nakama-cpp repository'
    required: true
runs:
  using: "composite"
  steps:
    - id: build
      run: |
        cmake --preset ${{ inputs.preset }} ${{ steps.cmake_args.outputs.args }}
        cmake --build ./build/${{ inputs.preset }} --config ${{ inputs.build_type }} --verbose
        cmake --install ./build/${{ inputs.preset }} --config ${{ inputs.build_type }}
      shell: bash
      working-directory: ${{ inputs.nakama-cpp-path }}
