name: 'Build test and run'
description: 'Build a test for nakama-cpp and run it'
inputs:
  preset:
    description: 'Configure preset name'
    required: true
  nakama-cpp-path:
    description: 'Relative path under $GITHUB_WORKSPACE to the nakama-cpp repository'
    required: true
  testrunner-pat:
    description: 'PAT to access the private Nakama testrunner'
    required: true
  build-type:
    description: The build type.
    required: true
  native-tool-options:
    description: 'Flags to pass to the underlying build system used by the CMake generator.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout nakama-client-testrunner
      uses: actions/checkout@v2
      with:
        repository: heroiclabs/nakama-client-testrunner
        token: ${{ inputs.testrunner-pat }}
        path: nakama-client-testrunner
    - name: Start docker containers for nakama-client-testrunner
      run: |
        docker-compose up -d
      working-directory: nakama-client-testrunner
      shell: bash
    - id: build
      run: |
        cmake --preset ${{ inputs.preset }}
        cmake --build ./build/${{ inputs.preset }} --config ${{ inputs.build-type }} --target install run -- ${{ inputs.native-tool-options }}
      shell: bash
      working-directory: ${{ inputs.nakama-cpp-path }}/test
