// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoc-gen-swagger/options/annotations.proto

#ifdef BUILD_GRPC_CLIENT

#include "protoc-gen-swagger/options/annotations.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_protoc_2dgen_2dswagger_2foptions_2fopenapiv2_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_protoc_2dgen_2dswagger_2foptions_2fopenapiv2_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_JSONSchema;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_protoc_2dgen_2dswagger_2foptions_2fopenapiv2_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_Tag;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_protoc_2dgen_2dswagger_2foptions_2fopenapiv2_2eproto ::google::protobuf::internal::SCCInfo<3> scc_info_Operation;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_protoc_2dgen_2dswagger_2foptions_2fopenapiv2_2eproto ::google::protobuf::internal::SCCInfo<3> scc_info_Schema;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_protoc_2dgen_2dswagger_2foptions_2fopenapiv2_2eproto ::google::protobuf::internal::SCCInfo<5> scc_info_Swagger;
}  // namespace protobuf_protoc_2dgen_2dswagger_2foptions_2fopenapiv2_2eproto
namespace grpc {
namespace gateway {
namespace protoc_gen_swagger {
namespace options {
}  // namespace options
}  // namespace protoc_gen_swagger
}  // namespace gateway
}  // namespace grpc
namespace protobuf_protoc_2dgen_2dswagger_2foptions_2fannotations_2eproto {
void InitDefaults() {
}

const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "protoc-gen-swagger/options/annotations.proto", schemas, file_default_instances, TableStruct::offsets,
      NULL, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n,protoc-gen-swagger/options/annotations"
      ".proto\022\'grpc.gateway.protoc_gen_swagger."
      "options\032*protoc-gen-swagger/options/open"
      "apiv2.proto\032 google/protobuf/descriptor."
      "proto:j\n\021openapiv2_swagger\022\034.google.prot"
      "obuf.FileOptions\030\222\010 \001(\01320.grpc.gateway.p"
      "rotoc_gen_swagger.options.Swagger:p\n\023ope"
      "napiv2_operation\022\036.google.protobuf.Metho"
      "dOptions\030\222\010 \001(\01322.grpc.gateway.protoc_ge"
      "n_swagger.options.Operation:k\n\020openapiv2"
      "_schema\022\037.google.protobuf.MessageOptions"
      "\030\222\010 \001(\0132/.grpc.gateway.protoc_gen_swagge"
      "r.options.Schema:e\n\ropenapiv2_tag\022\037.goog"
      "le.protobuf.ServiceOptions\030\222\010 \001(\0132,.grpc"
      ".gateway.protoc_gen_swagger.options.Tag:"
      "l\n\017openapiv2_field\022\035.google.protobuf.Fie"
      "ldOptions\030\222\010 \001(\01323.grpc.gateway.protoc_g"
      "en_swagger.options.JSONSchemaBCZAgithub."
      "com/grpc-ecosystem/grpc-gateway/protoc-g"
      "en-swagger/optionsb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 786);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protoc-gen-swagger/options/annotations.proto", &protobuf_RegisterTypes);
  ::protobuf_protoc_2dgen_2dswagger_2foptions_2fopenapiv2_2eproto::AddDescriptors();
  ::protobuf_google_2fprotobuf_2fdescriptor_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_protoc_2dgen_2dswagger_2foptions_2fannotations_2eproto
namespace grpc {
namespace gateway {
namespace protoc_gen_swagger {
namespace options {
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::grpc::gateway::protoc_gen_swagger::options::Swagger >, 11, false >
  openapiv2_swagger(kOpenapiv2SwaggerFieldNumber, *::grpc::gateway::protoc_gen_swagger::options::Swagger::internal_default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::grpc::gateway::protoc_gen_swagger::options::Operation >, 11, false >
  openapiv2_operation(kOpenapiv2OperationFieldNumber, *::grpc::gateway::protoc_gen_swagger::options::Operation::internal_default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::grpc::gateway::protoc_gen_swagger::options::Schema >, 11, false >
  openapiv2_schema(kOpenapiv2SchemaFieldNumber, *::grpc::gateway::protoc_gen_swagger::options::Schema::internal_default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::grpc::gateway::protoc_gen_swagger::options::Tag >, 11, false >
  openapiv2_tag(kOpenapiv2TagFieldNumber, *::grpc::gateway::protoc_gen_swagger::options::Tag::internal_default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::grpc::gateway::protoc_gen_swagger::options::JSONSchema >, 11, false >
  openapiv2_field(kOpenapiv2FieldFieldNumber, *::grpc::gateway::protoc_gen_swagger::options::JSONSchema::internal_default_instance());

// @@protoc_insertion_point(namespace_scope)
}  // namespace options
}  // namespace protoc_gen_swagger
}  // namespace gateway
}  // namespace grpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif // BUILD_GRPC_CLIENT
