// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoc-gen-swagger/options/annotations.proto

#ifndef PROTOBUF_INCLUDED_protoc_2dgen_2dswagger_2foptions_2fannotations_2eproto
#define PROTOBUF_INCLUDED_protoc_2dgen_2dswagger_2foptions_2fannotations_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "protoc-gen-swagger/options/openapiv2.pb.h"
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_protoc_2dgen_2dswagger_2foptions_2fannotations_2eproto 

namespace protobuf_protoc_2dgen_2dswagger_2foptions_2fannotations_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_protoc_2dgen_2dswagger_2foptions_2fannotations_2eproto
namespace grpc {
namespace gateway {
namespace protoc_gen_swagger {
namespace options {
}  // namespace options
}  // namespace protoc_gen_swagger
}  // namespace gateway
}  // namespace grpc
namespace grpc {
namespace gateway {
namespace protoc_gen_swagger {
namespace options {

// ===================================================================


// ===================================================================

static const int kOpenapiv2SwaggerFieldNumber = 1042;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::grpc::gateway::protoc_gen_swagger::options::Swagger >, 11, false >
  openapiv2_swagger;
static const int kOpenapiv2OperationFieldNumber = 1042;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::grpc::gateway::protoc_gen_swagger::options::Operation >, 11, false >
  openapiv2_operation;
static const int kOpenapiv2SchemaFieldNumber = 1042;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::grpc::gateway::protoc_gen_swagger::options::Schema >, 11, false >
  openapiv2_schema;
static const int kOpenapiv2TagFieldNumber = 1042;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::grpc::gateway::protoc_gen_swagger::options::Tag >, 11, false >
  openapiv2_tag;
static const int kOpenapiv2FieldFieldNumber = 1042;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::grpc::gateway::protoc_gen_swagger::options::JSONSchema >, 11, false >
  openapiv2_field;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace options
}  // namespace protoc_gen_swagger
}  // namespace gateway
}  // namespace grpc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_protoc_2dgen_2dswagger_2foptions_2fannotations_2eproto
