// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apigrpc.proto

#include "apigrpc.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace nakama {
namespace api {
}  // namespace api
}  // namespace nakama
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_apigrpc_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_apigrpc_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_apigrpc_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_apigrpc_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_apigrpc_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rapigrpc.proto\022\nnakama.api\032\034google/api/"
  "annotations.proto\032\033google/protobuf/empty"
  ".proto\032.protoc-gen-openapiv2/options/ann"
  "otations.proto\0321github.com/heroiclabs/na"
  "kama-common/api/api.proto2\262A\n\006Nakama\022W\n\n"
  "AddFriends\022\035.nakama.api.AddFriendsReques"
  "t\032\026.google.protobuf.Empty\"\022\202\323\344\223\002\014\"\n/v2/f"
  "riend\022k\n\rAddGroupUsers\022 .nakama.api.AddG"
  "roupUsersRequest\032\026.google.protobuf.Empty"
  "\" \202\323\344\223\002\032\"\030/v2/group/{group_id}/add\022\204\001\n\016S"
  "essionRefresh\022!.nakama.api.SessionRefres"
  "hRequest\032\023.nakama.api.Session\":\202\323\344\223\002 \"\033/"
  "v2/account/session/refresh:\001*\222A\021b\017\n\r\n\tBa"
  "sicAuth\022\000\022\223\001\n\021AuthenticateApple\022$.nakama"
  ".api.AuthenticateAppleRequest\032\023.nakama.a"
  "pi.Session\"C\202\323\344\223\002)\"\036/v2/account/authenti"
  "cate/apple:\007account\222A\021b\017\n\r\n\tBasicAuth\022\000\022"
  "\226\001\n\022AuthenticateCustom\022%.nakama.api.Auth"
  "enticateCustomRequest\032\023.nakama.api.Sessi"
  "on\"D\202\323\344\223\002*\"\037/v2/account/authenticate/cus"
  "tom:\007account\222A\021b\017\n\r\n\tBasicAuth\022\000\022\226\001\n\022Aut"
  "henticateDevice\022%.nakama.api.Authenticat"
  "eDeviceRequest\032\023.nakama.api.Session\"D\202\323\344"
  "\223\002*\"\037/v2/account/authenticate/device:\007ac"
  "count\222A\021b\017\n\r\n\tBasicAuth\022\000\022\223\001\n\021Authentica"
  "teEmail\022$.nakama.api.AuthenticateEmailRe"
  "quest\032\023.nakama.api.Session\"C\202\323\344\223\002)\"\036/v2/"
  "account/authenticate/email:\007account\222A\021b\017"
  "\n\r\n\tBasicAuth\022\000\022\234\001\n\024AuthenticateFacebook"
  "\022\'.nakama.api.AuthenticateFacebookReques"
  "t\032\023.nakama.api.Session\"F\202\323\344\223\002,\"!/v2/acco"
  "unt/authenticate/facebook:\007account\222A\021b\017\n"
  "\r\n\tBasicAuth\022\000\022\275\001\n\037AuthenticateFacebookI"
  "nstantGame\0222.nakama.api.AuthenticateFace"
  "bookInstantGameRequest\032\023.nakama.api.Sess"
  "ion\"Q\202\323\344\223\0027\",/v2/account/authenticate/fa"
  "cebookinstantgame:\007account\222A\021b\017\n\r\n\tBasic"
  "Auth\022\000\022\242\001\n\026AuthenticateGameCenter\022).naka"
  "ma.api.AuthenticateGameCenterRequest\032\023.n"
  "akama.api.Session\"H\202\323\344\223\002.\"#/v2/account/a"
  "uthenticate/gamecenter:\007account\222A\021b\017\n\r\n\t"
  "BasicAuth\022\000\022\226\001\n\022AuthenticateGoogle\022%.nak"
  "ama.api.AuthenticateGoogleRequest\032\023.naka"
  "ma.api.Session\"D\202\323\344\223\002*\"\037/v2/account/auth"
  "enticate/google:\007account\222A\021b\017\n\r\n\tBasicAu"
  "th\022\000\022\223\001\n\021AuthenticateSteam\022$.nakama.api."
  "AuthenticateSteamRequest\032\023.nakama.api.Se"
  "ssion\"C\202\323\344\223\002)\"\036/v2/account/authenticate/"
  "steam:\007account\222A\021b\017\n\r\n\tBasicAuth\022\000\022k\n\rBa"
  "nGroupUsers\022 .nakama.api.BanGroupUsersRe"
  "quest\032\026.google.protobuf.Empty\" \202\323\344\223\002\032\"\030/"
  "v2/group/{group_id}/ban\022a\n\014BlockFriends\022"
  "\037.nakama.api.BlockFriendsRequest\032\026.googl"
  "e.protobuf.Empty\"\030\202\323\344\223\002\022\"\020/v2/friend/blo"
  "ck\022V\n\013CreateGroup\022\036.nakama.api.CreateGro"
  "upRequest\032\021.nakama.api.Group\"\024\202\323\344\223\002\016\"\t/v"
  "2/group:\001*\022]\n\rDeleteFriends\022 .nakama.api"
  ".DeleteFriendsRequest\032\026.google.protobuf."
  "Empty\"\022\202\323\344\223\002\014*\n/v2/friend\022c\n\013DeleteGroup"
  "\022\036.nakama.api.DeleteGroupRequest\032\026.googl"
  "e.protobuf.Empty\"\034\202\323\344\223\002\026*\024/v2/group/{gro"
  "up_id}\022\207\001\n\027DeleteLeaderboardRecord\022*.nak"
  "ama.api.DeleteLeaderboardRecordRequest\032\026"
  ".google.protobuf.Empty\"(\202\323\344\223\002\"* /v2/lead"
  "erboard/{leaderboard_id}\022o\n\023DeleteNotifi"
  "cations\022&.nakama.api.DeleteNotifications"
  "Request\032\026.google.protobuf.Empty\"\030\202\323\344\223\002\022*"
  "\020/v2/notification\022v\n\024DeleteStorageObject"
  "s\022\'.nakama.api.DeleteStorageObjectsReque"
  "st\032\026.google.protobuf.Empty\"\035\202\323\344\223\002\027\032\022/v2/"
  "storage/delete:\001*\022H\n\005Event\022\021.nakama.api."
  "Event\032\026.google.protobuf.Empty\"\024\202\323\344\223\002\016\"\t/"
  "v2/event:\001*\022N\n\nGetAccount\022\026.google.proto"
  "buf.Empty\032\023.nakama.api.Account\"\023\202\323\344\223\002\r\022\013"
  "/v2/account\022L\n\010GetUsers\022\033.nakama.api.Get"
  "UsersRequest\032\021.nakama.api.Users\"\020\202\323\344\223\002\n\022"
  "\010/v2/user\022S\n\013Healthcheck\022\026.google.protob"
  "uf.Empty\032\026.google.protobuf.Empty\"\024\202\323\344\223\002\016"
  "\022\014/healthcheck\022\177\n\025ImportFacebookFriends\022"
  "(.nakama.api.ImportFacebookFriendsReques"
  "t\032\026.google.protobuf.Empty\"$\202\323\344\223\002\036\"\023/v2/f"
  "riend/facebook:\007account\022v\n\022ImportSteamFr"
  "iends\022%.nakama.api.ImportSteamFriendsReq"
  "uest\032\026.google.protobuf.Empty\"!\202\323\344\223\002\033\"\020/v"
  "2/friend/steam:\007account\022d\n\tJoinGroup\022\034.n"
  "akama.api.JoinGroupRequest\032\026.google.prot"
  "obuf.Empty\"!\202\323\344\223\002\033\"\031/v2/group/{group_id}"
  "/join\022x\n\016JoinTournament\022!.nakama.api.Joi"
  "nTournamentRequest\032\026.google.protobuf.Emp"
  "ty\"+\202\323\344\223\002%\"#/v2/tournament/{tournament_i"
  "d}/join\022n\n\016KickGroupUsers\022!.nakama.api.K"
  "ickGroupUsersRequest\032\026.google.protobuf.E"
  "mpty\"!\202\323\344\223\002\033\"\031/v2/group/{group_id}/kick\022"
  "g\n\nLeaveGroup\022\035.nakama.api.LeaveGroupReq"
  "uest\032\026.google.protobuf.Empty\"\"\202\323\344\223\002\034\"\032/v"
  "2/group/{group_id}/leave\022`\n\tLinkApple\022\030."
  "nakama.api.AccountApple\032\026.google.protobu"
  "f.Empty\"!\202\323\344\223\002\033\"\026/v2/account/link/apple:"
  "\001*\022c\n\nLinkCustom\022\031.nakama.api.AccountCus"
  "tom\032\026.google.protobuf.Empty\"\"\202\323\344\223\002\034\"\027/v2"
  "/account/link/custom:\001*\022c\n\nLinkDevice\022\031."
  "nakama.api.AccountDevice\032\026.google.protob"
  "uf.Empty\"\"\202\323\344\223\002\034\"\027/v2/account/link/devic"
  "e:\001*\022`\n\tLinkEmail\022\030.nakama.api.AccountEm"
  "ail\032\026.google.protobuf.Empty\"!\202\323\344\223\002\033\"\026/v2"
  "/account/link/email:\001*\022s\n\014LinkFacebook\022\037"
  ".nakama.api.LinkFacebookRequest\032\026.google"
  ".protobuf.Empty\"*\202\323\344\223\002$\"\031/v2/account/lin"
  "k/facebook:\007account\022\212\001\n\027LinkFacebookInst"
  "antGame\022&.nakama.api.AccountFacebookInst"
  "antGame\032\026.google.protobuf.Empty\"/\202\323\344\223\002)\""
  "$/v2/account/link/facebookinstantgame:\001*"
  "\022o\n\016LinkGameCenter\022\035.nakama.api.AccountG"
  "ameCenter\032\026.google.protobuf.Empty\"&\202\323\344\223\002"
  " \"\033/v2/account/link/gamecenter:\001*\022c\n\nLin"
  "kGoogle\022\031.nakama.api.AccountGoogle\032\026.goo"
  "gle.protobuf.Empty\"\"\202\323\344\223\002\034\"\027/v2/account/"
  "link/google:\001*\022d\n\tLinkSteam\022\034.nakama.api"
  ".LinkSteamRequest\032\026.google.protobuf.Empt"
  "y\"!\202\323\344\223\002\033\"\026/v2/account/link/steam:\001*\022\177\n\023"
  "ListChannelMessages\022&.nakama.api.ListCha"
  "nnelMessagesRequest\032\036.nakama.api.Channel"
  "MessageList\" \202\323\344\223\002\032\022\030/v2/channel/{channe"
  "l_id}\022Y\n\013ListFriends\022\036.nakama.api.ListFr"
  "iendsRequest\032\026.nakama.api.FriendList\"\022\202\323"
  "\344\223\002\014\022\n/v2/friend\022U\n\nListGroups\022\035.nakama."
  "api.ListGroupsRequest\032\025.nakama.api.Group"
  "List\"\021\202\323\344\223\002\013\022\t/v2/group\022q\n\016ListGroupUser"
  "s\022!.nakama.api.ListGroupUsersRequest\032\031.n"
  "akama.api.GroupUserList\"!\202\323\344\223\002\033\022\031/v2/gro"
  "up/{group_id}/user\022\220\001\n\026ListLeaderboardRe"
  "cords\022).nakama.api.ListLeaderboardRecord"
  "sRequest\032!.nakama.api.LeaderboardRecordL"
  "ist\"(\202\323\344\223\002\"\022 /v2/leaderboard/{leaderboar"
  "d_id}\022\267\001\n!ListLeaderboardRecordsAroundOw"
  "ner\0224.nakama.api.ListLeaderboardRecordsA"
  "roundOwnerRequest\032!.nakama.api.Leaderboa"
  "rdRecordList\"9\202\323\344\223\0023\0221/v2/leaderboard/{l"
  "eaderboard_id}/owner/{owner_id}\022W\n\013ListM"
  "atches\022\036.nakama.api.ListMatchesRequest\032\025"
  ".nakama.api.MatchList\"\021\202\323\344\223\002\013\022\t/v2/match"
  "\022q\n\021ListNotifications\022$.nakama.api.ListN"
  "otificationsRequest\032\034.nakama.api.Notific"
  "ationList\"\030\202\323\344\223\002\022\022\020/v2/notification\022\242\001\n\022"
  "ListStorageObjects\022%.nakama.api.ListStor"
  "ageObjectsRequest\032\035.nakama.api.StorageOb"
  "jectList\"F\202\323\344\223\002@\022\030/v2/storage/{collectio"
  "n}Z$\022\"/v2/storage/{collection}/{user_id}"
  "\022i\n\017ListTournaments\022\".nakama.api.ListTou"
  "rnamentsRequest\032\032.nakama.api.TournamentL"
  "ist\"\026\202\323\344\223\002\020\022\016/v2/tournament\022\213\001\n\025ListTour"
  "namentRecords\022(.nakama.api.ListTournamen"
  "tRecordsRequest\032 .nakama.api.TournamentR"
  "ecordList\"&\202\323\344\223\002 \022\036/v2/tournament/{tourn"
  "ament_id}\022\262\001\n ListTournamentRecordsAroun"
  "dOwner\0223.nakama.api.ListTournamentRecord"
  "sAroundOwnerRequest\032 .nakama.api.Tournam"
  "entRecordList\"7\202\323\344\223\0021\022//v2/tournament/{t"
  "ournament_id}/owner/{owner_id}\022p\n\016ListUs"
  "erGroups\022!.nakama.api.ListUserGroupsRequ"
  "est\032\031.nakama.api.UserGroupList\" \202\323\344\223\002\032\022\030"
  "/v2/user/{user_id}/group\022w\n\021PromoteGroup"
  "Users\022$.nakama.api.PromoteGroupUsersRequ"
  "est\032\026.google.protobuf.Empty\"$\202\323\344\223\002\036\"\034/v2"
  "/group/{group_id}/promote\022t\n\020DemoteGroup"
  "Users\022#.nakama.api.DemoteGroupUsersReque"
  "st\032\026.google.protobuf.Empty\"#\202\323\344\223\002\035\"\033/v2/"
  "group/{group_id}/demote\022o\n\022ReadStorageOb"
  "jects\022%.nakama.api.ReadStorageObjectsReq"
  "uest\032\032.nakama.api.StorageObjects\"\026\202\323\344\223\002\020"
  "\"\013/v2/storage:\001*\022\177\n\007RpcFunc\022\017.nakama.api"
  ".Rpc\032\017.nakama.api.Rpc\"R\202\323\344\223\002\'\"\014/v2/rpc/{"
  "id}:\007payloadZ\016\022\014/v2/rpc/{id}\222A\"b \n\017\n\013Htt"
  "pKeyAuth\022\000\n\r\n\tBearerJwt\022\000\022d\n\013UnlinkApple"
  "\022\030.nakama.api.AccountApple\032\026.google.prot"
  "obuf.Empty\"#\202\323\344\223\002\035\"\030/v2/account/unlink/a"
  "pple:\001*\022g\n\014UnlinkCustom\022\031.nakama.api.Acc"
  "ountCustom\032\026.google.protobuf.Empty\"$\202\323\344\223"
  "\002\036\"\031/v2/account/unlink/custom:\001*\022g\n\014Unli"
  "nkDevice\022\031.nakama.api.AccountDevice\032\026.go"
  "ogle.protobuf.Empty\"$\202\323\344\223\002\036\"\031/v2/account"
  "/unlink/device:\001*\022d\n\013UnlinkEmail\022\030.nakam"
  "a.api.AccountEmail\032\026.google.protobuf.Emp"
  "ty\"#\202\323\344\223\002\035\"\030/v2/account/unlink/email:\001*\022"
  "m\n\016UnlinkFacebook\022\033.nakama.api.AccountFa"
  "cebook\032\026.google.protobuf.Empty\"&\202\323\344\223\002 \"\033"
  "/v2/account/unlink/facebook:\001*\022\216\001\n\031Unlin"
  "kFacebookInstantGame\022&.nakama.api.Accoun"
  "tFacebookInstantGame\032\026.google.protobuf.E"
  "mpty\"1\202\323\344\223\002+\"&/v2/account/unlink/faceboo"
  "kinstantgame:\001*\022s\n\020UnlinkGameCenter\022\035.na"
  "kama.api.AccountGameCenter\032\026.google.prot"
  "obuf.Empty\"(\202\323\344\223\002\"\"\035/v2/account/unlink/g"
  "amecenter:\001*\022g\n\014UnlinkGoogle\022\031.nakama.ap"
  "i.AccountGoogle\032\026.google.protobuf.Empty\""
  "$\202\323\344\223\002\036\"\031/v2/account/unlink/google:\001*\022d\n"
  "\013UnlinkSteam\022\030.nakama.api.AccountSteam\032\026"
  ".google.protobuf.Empty\"#\202\323\344\223\002\035\"\030/v2/acco"
  "unt/unlink/steam:\001*\022a\n\rUpdateAccount\022 .n"
  "akama.api.UpdateAccountRequest\032\026.google."
  "protobuf.Empty\"\026\202\323\344\223\002\020\032\013/v2/account:\001*\022f"
  "\n\013UpdateGroup\022\036.nakama.api.UpdateGroupRe"
  "quest\032\026.google.protobuf.Empty\"\037\202\323\344\223\002\031\032\024/"
  "v2/group/{group_id}:\001*\022\224\001\n\026WriteLeaderbo"
  "ardRecord\022).nakama.api.WriteLeaderboardR"
  "ecordRequest\032\035.nakama.api.LeaderboardRec"
  "ord\"0\202\323\344\223\002*\" /v2/leaderboard/{leaderboar"
  "d_id}:\006record\022t\n\023WriteStorageObjects\022&.n"
  "akama.api.WriteStorageObjectsRequest\032\035.n"
  "akama.api.StorageObjectAcks\"\026\202\323\344\223\002\020\032\013/v2"
  "/storage:\001*\022\220\001\n\025WriteTournamentRecord\022(."
  "nakama.api.WriteTournamentRecordRequest\032"
  "\035.nakama.api.LeaderboardRecord\".\202\323\344\223\002(\032\036"
  "/v2/tournament/{tournament_id}:\006recordB\247"
  "\003\n\031com.heroiclabs.nakama.apiB\rNakamaApiG"
  "rpcP\001Z\'github.com/heroiclabs/nakama/v3/a"
  "pigrpc\252\002\017Nakama.Protobuf\222A\274\002\022u\n\rNakama A"
  "PI v2\"_\n!The Nakama Authors & Contributo"
  "rs\022$https://github.com/heroiclabs/nakama"
  "\032\024hello@heroiclabs.com2\0032.0\032\016127.0.0.1:7"
  "350*\001\0012\020application/json:\020application/js"
  "onZ\?\n\017\n\tBasicAuth\022\002\010\001\n\r\n\tBearerJwt\022\000\n\035\n\013"
  "HttpKeyAuth\022\016\010\002\032\010http_key \002b\017\n\r\n\tBearerJ"
  "wt\022\000r:\n\033Nakama server documentation\022\033htt"
  "ps://heroiclabs.com/docsb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_apigrpc_2eproto_deps[4] = {
  &::descriptor_table_github_2ecom_2fheroiclabs_2fnakama_2dcommon_2fapi_2fapi_2eproto,
  &::descriptor_table_google_2fapi_2fannotations_2eproto,
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
  &::descriptor_table_protoc_2dgen_2dopenapiv2_2foptions_2fannotations_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_apigrpc_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_apigrpc_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_apigrpc_2eproto = {
  false, false, descriptor_table_protodef_apigrpc_2eproto, "apigrpc.proto", 8992,
  &descriptor_table_apigrpc_2eproto_once, descriptor_table_apigrpc_2eproto_sccs, descriptor_table_apigrpc_2eproto_deps, 0, 4,
  schemas, file_default_instances, TableStruct_apigrpc_2eproto::offsets,
  file_level_metadata_apigrpc_2eproto, 0, file_level_enum_descriptors_apigrpc_2eproto, file_level_service_descriptors_apigrpc_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_apigrpc_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_apigrpc_2eproto)), true);
namespace nakama {
namespace api {

// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace nakama
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
