name: 'Build platform and upload'
description: 'Build for a single platform and upload the resulting artifact.'
inputs:
  preset:
    description: 'Configure preset name'
    required: true
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to the nakama-cpp repository'
    required: true
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v3
      with:
        path: vcpkg
        repository: microsoft/vcpkg
        fetch-depth: 0
    - uses: ${{ inputs.path }}/nakama-cpp/.github/actions/setup-vcpkg
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        path: vcpkg
    - id: build
      uses: ./nakama-cpp/.github/actions/cmake-build
      with:
        preset: ${{ inputs.preset }}
        path: nakama-cpp
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.build.outputs.artifact_name }}
        path: ${{ steps.build.outputs.artifact_name }}.7z
        retention-days: 2
    - if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.build.outputs.artifact_name }}-workdir-debug
        path: |
          ./${{ inputs.path }}/build
          ./vcpkg/buildtrees
        retention-days: 1

