name: 'Build platform and upload'
description: 'Build for a single platform and upload the resulting artifact.'
inputs:
  preset:
    description: 'Configure preset name'
    required: true
  nakama-cpp-path:
    description: 'Relative path under $GITHUB_WORKSPACE to the nakama-cpp repository'
    required: true
  github_token:
    description: 'Github token'
    required: true
  build_type:
    description: 'Build config: MinSizeRel or Debug'
    required: true
    default: 'MinSizeRel'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        path: vcpkg
        repository: microsoft/vcpkg
        fetch-depth: 0
        # workaround: we can't use local inputs in values for `uses` keys, so copy actions to the root workspace
        # we can get around this by creating an internal actions repo if we want.
    - run: "cp -r ./.github/actions ${GITHUB_WORKSPACE}/.github"
      shell: bash
      working-directory: ${{ inputs.nakama-cpp-path }}
    - uses: ./.github/actions/setup-vcpkg
      with:
        github_token: ${{ inputs.github_token }}
        working-directory: vcpkg
    - id: build
      uses: ./.github/actions/cmake-build
      with:
        preset: ${{ inputs.preset }}
        working-directory: ${{ inputs.nakama-cpp-path }}
        build_type: ${{ inputs.build_type }}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.build.outputs.artifact_name }}
        path: ${{ steps.build.outputs.artifact_name }}.7z
        retention-days: 2
    - if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.build.outputs.artifact_name }}-workdir-debug
        path: |
          ./${{ inputs.nakama-cpp-path }}/build
          ./vcpkg/buildtrees
        retention-days: 1

