if (EXISTS "${CMAKE_SOURCE_DIR}/CMakeUserPresets.json" AND EXISTS "${CMAKE_SOURCE_DIR}/submodules/private/CMakeUserPresets.json")
    file(MD5 "${CMAKE_SOURCE_DIR}/CMakeUserPresets.json" LOCAL_USER_PRESETS_MD5)
    file(MD5 "${CMAKE_SOURCE_DIR}/submodules/private/CMakeUserPresets.json" PRIVATE_USER_PRESETS_MD5)
    if (NOT LOCAL_USER_PRESETS_MD5 STREQUAL PRIVATE_USER_PRESETS_MD5)
        message(FATAL_ERROR "CMakeUserPresets.json from private repo was updated, but not copied to the project dir.")
    endif()
endif()
unset(LOCAL_USER_PRESETS_MD5)
unset(PRIVATE_USER_PRESETS_MD5)
