// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/heroiclabs/nakama/apigrpc/apigrpc.proto

#ifdef BUILD_GRPC_CLIENT

#include "github.com/heroiclabs/nakama/apigrpc/apigrpc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace nakama {
namespace api {
}  // namespace api
}  // namespace nakama
namespace protobuf_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto {
void InitDefaults() {
}

const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "github.com/heroiclabs/nakama/apigrpc/apigrpc.proto", schemas, file_default_instances, TableStruct::offsets,
      NULL, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n2github.com/heroiclabs/nakama/apigrpc/a"
      "pigrpc.proto\022\nnakama.api\032\034google/api/ann"
      "otations.proto\032\033google/protobuf/empty.pr"
      "oto\032,protoc-gen-swagger/options/annotati"
      "ons.proto\0321github.com/heroiclabs/nakama-"
      "common/api/api.proto2\257\?\n\006Nakama\022W\n\nAddFr"
      "iends\022\035.nakama.api.AddFriendsRequest\032\026.g"
      "oogle.protobuf.Empty\"\022\202\323\344\223\002\014\"\n/v2/friend"
      "\022k\n\rAddGroupUsers\022 .nakama.api.AddGroupU"
      "sersRequest\032\026.google.protobuf.Empty\" \202\323\344"
      "\223\002\032\"\030/v2/group/{group_id}/add\022\223\001\n\021Authen"
      "ticateApple\022$.nakama.api.AuthenticateApp"
      "leRequest\032\023.nakama.api.Session\"C\202\323\344\223\002)\"\036"
      "/v2/account/authenticate/apple:\007account\222"
      "A\021b\017\n\r\n\tBasicAuth\022\000\022\226\001\n\022AuthenticateCust"
      "om\022%.nakama.api.AuthenticateCustomReques"
      "t\032\023.nakama.api.Session\"D\202\323\344\223\002*\"\037/v2/acco"
      "unt/authenticate/custom:\007account\222A\021b\017\n\r\n"
      "\tBasicAuth\022\000\022\226\001\n\022AuthenticateDevice\022%.na"
      "kama.api.AuthenticateDeviceRequest\032\023.nak"
      "ama.api.Session\"D\202\323\344\223\002*\"\037/v2/account/aut"
      "henticate/device:\007account\222A\021b\017\n\r\n\tBasicA"
      "uth\022\000\022\223\001\n\021AuthenticateEmail\022$.nakama.api"
      ".AuthenticateEmailRequest\032\023.nakama.api.S"
      "ession\"C\202\323\344\223\002)\"\036/v2/account/authenticate"
      "/email:\007account\222A\021b\017\n\r\n\tBasicAuth\022\000\022\234\001\n\024"
      "AuthenticateFacebook\022\'.nakama.api.Authen"
      "ticateFacebookRequest\032\023.nakama.api.Sessi"
      "on\"F\202\323\344\223\002,\"!/v2/account/authenticate/fac"
      "ebook:\007account\222A\021b\017\n\r\n\tBasicAuth\022\000\022\275\001\n\037A"
      "uthenticateFacebookInstantGame\0222.nakama."
      "api.AuthenticateFacebookInstantGameReque"
      "st\032\023.nakama.api.Session\"Q\202\323\344\223\0027\",/v2/acc"
      "ount/authenticate/facebookinstantgame:\007a"
      "ccount\222A\021b\017\n\r\n\tBasicAuth\022\000\022\242\001\n\026Authentic"
      "ateGameCenter\022).nakama.api.AuthenticateG"
      "ameCenterRequest\032\023.nakama.api.Session\"H\202"
      "\323\344\223\002.\"#/v2/account/authenticate/gamecent"
      "er:\007account\222A\021b\017\n\r\n\tBasicAuth\022\000\022\226\001\n\022Auth"
      "enticateGoogle\022%.nakama.api.Authenticate"
      "GoogleRequest\032\023.nakama.api.Session\"D\202\323\344\223"
      "\002*\"\037/v2/account/authenticate/google:\007acc"
      "ount\222A\021b\017\n\r\n\tBasicAuth\022\000\022\223\001\n\021Authenticat"
      "eSteam\022$.nakama.api.AuthenticateSteamReq"
      "uest\032\023.nakama.api.Session\"C\202\323\344\223\002)\"\036/v2/a"
      "ccount/authenticate/steam:\007account\222A\021b\017\n"
      "\r\n\tBasicAuth\022\000\022k\n\rBanGroupUsers\022 .nakama"
      ".api.BanGroupUsersRequest\032\026.google.proto"
      "buf.Empty\" \202\323\344\223\002\032\"\030/v2/group/{group_id}/"
      "ban\022a\n\014BlockFriends\022\037.nakama.api.BlockFr"
      "iendsRequest\032\026.google.protobuf.Empty\"\030\202\323"
      "\344\223\002\022\"\020/v2/friend/block\022V\n\013CreateGroup\022\036."
      "nakama.api.CreateGroupRequest\032\021.nakama.a"
      "pi.Group\"\024\202\323\344\223\002\016\"\t/v2/group:\001*\022]\n\rDelete"
      "Friends\022 .nakama.api.DeleteFriendsReques"
      "t\032\026.google.protobuf.Empty\"\022\202\323\344\223\002\014*\n/v2/f"
      "riend\022c\n\013DeleteGroup\022\036.nakama.api.Delete"
      "GroupRequest\032\026.google.protobuf.Empty\"\034\202\323"
      "\344\223\002\026*\024/v2/group/{group_id}\022\207\001\n\027DeleteLea"
      "derboardRecord\022*.nakama.api.DeleteLeader"
      "boardRecordRequest\032\026.google.protobuf.Emp"
      "ty\"(\202\323\344\223\002\"* /v2/leaderboard/{leaderboard"
      "_id}\022o\n\023DeleteNotifications\022&.nakama.api"
      ".DeleteNotificationsRequest\032\026.google.pro"
      "tobuf.Empty\"\030\202\323\344\223\002\022*\020/v2/notification\022v\n"
      "\024DeleteStorageObjects\022\'.nakama.api.Delet"
      "eStorageObjectsRequest\032\026.google.protobuf"
      ".Empty\"\035\202\323\344\223\002\027\032\022/v2/storage/delete:\001*\022H\n"
      "\005Event\022\021.nakama.api.Event\032\026.google.proto"
      "buf.Empty\"\024\202\323\344\223\002\016\"\t/v2/event:\001*\022N\n\nGetAc"
      "count\022\026.google.protobuf.Empty\032\023.nakama.a"
      "pi.Account\"\023\202\323\344\223\002\r\022\013/v2/account\022L\n\010GetUs"
      "ers\022\033.nakama.api.GetUsersRequest\032\021.nakam"
      "a.api.Users\"\020\202\323\344\223\002\n\022\010/v2/user\022S\n\013Healthc"
      "heck\022\026.google.protobuf.Empty\032\026.google.pr"
      "otobuf.Empty\"\024\202\323\344\223\002\016\022\014/healthcheck\022\177\n\025Im"
      "portFacebookFriends\022(.nakama.api.ImportF"
      "acebookFriendsRequest\032\026.google.protobuf."
      "Empty\"$\202\323\344\223\002\036\"\023/v2/friend/facebook:\007acco"
      "unt\022d\n\tJoinGroup\022\034.nakama.api.JoinGroupR"
      "equest\032\026.google.protobuf.Empty\"!\202\323\344\223\002\033\"\031"
      "/v2/group/{group_id}/join\022x\n\016JoinTournam"
      "ent\022!.nakama.api.JoinTournamentRequest\032\026"
      ".google.protobuf.Empty\"+\202\323\344\223\002%\"#/v2/tour"
      "nament/{tournament_id}/join\022n\n\016KickGroup"
      "Users\022!.nakama.api.KickGroupUsersRequest"
      "\032\026.google.protobuf.Empty\"!\202\323\344\223\002\033\"\031/v2/gr"
      "oup/{group_id}/kick\022g\n\nLeaveGroup\022\035.naka"
      "ma.api.LeaveGroupRequest\032\026.google.protob"
      "uf.Empty\"\"\202\323\344\223\002\034\"\032/v2/group/{group_id}/l"
      "eave\022`\n\tLinkApple\022\030.nakama.api.AccountAp"
      "ple\032\026.google.protobuf.Empty\"!\202\323\344\223\002\033\"\026/v2"
      "/account/link/apple:\001*\022c\n\nLinkCustom\022\031.n"
      "akama.api.AccountCustom\032\026.google.protobu"
      "f.Empty\"\"\202\323\344\223\002\034\"\027/v2/account/link/custom"
      ":\001*\022c\n\nLinkDevice\022\031.nakama.api.AccountDe"
      "vice\032\026.google.protobuf.Empty\"\"\202\323\344\223\002\034\"\027/v"
      "2/account/link/device:\001*\022`\n\tLinkEmail\022\030."
      "nakama.api.AccountEmail\032\026.google.protobu"
      "f.Empty\"!\202\323\344\223\002\033\"\026/v2/account/link/email:"
      "\001*\022s\n\014LinkFacebook\022\037.nakama.api.LinkFace"
      "bookRequest\032\026.google.protobuf.Empty\"*\202\323\344"
      "\223\002$\"\031/v2/account/link/facebook:\007account\022"
      "\212\001\n\027LinkFacebookInstantGame\022&.nakama.api"
      ".AccountFacebookInstantGame\032\026.google.pro"
      "tobuf.Empty\"/\202\323\344\223\002)\"$/v2/account/link/fa"
      "cebookinstantgame:\001*\022o\n\016LinkGameCenter\022\035"
      ".nakama.api.AccountGameCenter\032\026.google.p"
      "rotobuf.Empty\"&\202\323\344\223\002 \"\033/v2/account/link/"
      "gamecenter:\001*\022c\n\nLinkGoogle\022\031.nakama.api"
      ".AccountGoogle\032\026.google.protobuf.Empty\"\""
      "\202\323\344\223\002\034\"\027/v2/account/link/google:\001*\022`\n\tLi"
      "nkSteam\022\030.nakama.api.AccountSteam\032\026.goog"
      "le.protobuf.Empty\"!\202\323\344\223\002\033\"\026/v2/account/l"
      "ink/steam:\001*\022\177\n\023ListChannelMessages\022&.na"
      "kama.api.ListChannelMessagesRequest\032\036.na"
      "kama.api.ChannelMessageList\" \202\323\344\223\002\032\022\030/v2"
      "/channel/{channel_id}\022Y\n\013ListFriends\022\036.n"
      "akama.api.ListFriendsRequest\032\026.nakama.ap"
      "i.FriendList\"\022\202\323\344\223\002\014\022\n/v2/friend\022U\n\nList"
      "Groups\022\035.nakama.api.ListGroupsRequest\032\025."
      "nakama.api.GroupList\"\021\202\323\344\223\002\013\022\t/v2/group\022"
      "q\n\016ListGroupUsers\022!.nakama.api.ListGroup"
      "UsersRequest\032\031.nakama.api.GroupUserList\""
      "!\202\323\344\223\002\033\022\031/v2/group/{group_id}/user\022\220\001\n\026L"
      "istLeaderboardRecords\022).nakama.api.ListL"
      "eaderboardRecordsRequest\032!.nakama.api.Le"
      "aderboardRecordList\"(\202\323\344\223\002\"\022 /v2/leaderb"
      "oard/{leaderboard_id}\022\267\001\n!ListLeaderboar"
      "dRecordsAroundOwner\0224.nakama.api.ListLea"
      "derboardRecordsAroundOwnerRequest\032!.naka"
      "ma.api.LeaderboardRecordList\"9\202\323\344\223\0023\0221/v"
      "2/leaderboard/{leaderboard_id}/owner/{ow"
      "ner_id}\022W\n\013ListMatches\022\036.nakama.api.List"
      "MatchesRequest\032\025.nakama.api.MatchList\"\021\202"
      "\323\344\223\002\013\022\t/v2/match\022q\n\021ListNotifications\022$."
      "nakama.api.ListNotificationsRequest\032\034.na"
      "kama.api.NotificationList\"\030\202\323\344\223\002\022\022\020/v2/n"
      "otification\022\242\001\n\022ListStorageObjects\022%.nak"
      "ama.api.ListStorageObjectsRequest\032\035.naka"
      "ma.api.StorageObjectList\"F\202\323\344\223\002@\022\030/v2/st"
      "orage/{collection}Z$\022\"/v2/storage/{colle"
      "ction}/{user_id}\022i\n\017ListTournaments\022\".na"
      "kama.api.ListTournamentsRequest\032\032.nakama"
      ".api.TournamentList\"\026\202\323\344\223\002\020\022\016/v2/tournam"
      "ent\022\213\001\n\025ListTournamentRecords\022(.nakama.a"
      "pi.ListTournamentRecordsRequest\032 .nakama"
      ".api.TournamentRecordList\"&\202\323\344\223\002 \022\036/v2/t"
      "ournament/{tournament_id}\022\262\001\n ListTourna"
      "mentRecordsAroundOwner\0223.nakama.api.List"
      "TournamentRecordsAroundOwnerRequest\032 .na"
      "kama.api.TournamentRecordList\"7\202\323\344\223\0021\022//"
      "v2/tournament/{tournament_id}/owner/{own"
      "er_id}\022p\n\016ListUserGroups\022!.nakama.api.Li"
      "stUserGroupsRequest\032\031.nakama.api.UserGro"
      "upList\" \202\323\344\223\002\032\022\030/v2/user/{user_id}/group"
      "\022w\n\021PromoteGroupUsers\022$.nakama.api.Promo"
      "teGroupUsersRequest\032\026.google.protobuf.Em"
      "pty\"$\202\323\344\223\002\036\"\034/v2/group/{group_id}/promot"
      "e\022t\n\020DemoteGroupUsers\022#.nakama.api.Demot"
      "eGroupUsersRequest\032\026.google.protobuf.Emp"
      "ty\"#\202\323\344\223\002\035\"\033/v2/group/{group_id}/demote\022"
      "o\n\022ReadStorageObjects\022%.nakama.api.ReadS"
      "torageObjectsRequest\032\032.nakama.api.Storag"
      "eObjects\"\026\202\323\344\223\002\020\"\013/v2/storage:\001*\022\177\n\007RpcF"
      "unc\022\017.nakama.api.Rpc\032\017.nakama.api.Rpc\"R\202"
      "\323\344\223\002\'\"\014/v2/rpc/{id}:\007payloadZ\016\022\014/v2/rpc/"
      "{id}\222A\"b \n\017\n\013HttpKeyAuth\022\000\n\r\n\tBearerJwt\022"
      "\000\022d\n\013UnlinkApple\022\030.nakama.api.AccountApp"
      "le\032\026.google.protobuf.Empty\"#\202\323\344\223\002\035\"\030/v2/"
      "account/unlink/apple:\001*\022g\n\014UnlinkCustom\022"
      "\031.nakama.api.AccountCustom\032\026.google.prot"
      "obuf.Empty\"$\202\323\344\223\002\036\"\031/v2/account/unlink/c"
      "ustom:\001*\022g\n\014UnlinkDevice\022\031.nakama.api.Ac"
      "countDevice\032\026.google.protobuf.Empty\"$\202\323\344"
      "\223\002\036\"\031/v2/account/unlink/device:\001*\022d\n\013Unl"
      "inkEmail\022\030.nakama.api.AccountEmail\032\026.goo"
      "gle.protobuf.Empty\"#\202\323\344\223\002\035\"\030/v2/account/"
      "unlink/email:\001*\022m\n\016UnlinkFacebook\022\033.naka"
      "ma.api.AccountFacebook\032\026.google.protobuf"
      ".Empty\"&\202\323\344\223\002 \"\033/v2/account/unlink/faceb"
      "ook:\001*\022\216\001\n\031UnlinkFacebookInstantGame\022&.n"
      "akama.api.AccountFacebookInstantGame\032\026.g"
      "oogle.protobuf.Empty\"1\202\323\344\223\002+\"&/v2/accoun"
      "t/unlink/facebookinstantgame:\001*\022s\n\020Unlin"
      "kGameCenter\022\035.nakama.api.AccountGameCent"
      "er\032\026.google.protobuf.Empty\"(\202\323\344\223\002\"\"\035/v2/"
      "account/unlink/gamecenter:\001*\022g\n\014UnlinkGo"
      "ogle\022\031.nakama.api.AccountGoogle\032\026.google"
      ".protobuf.Empty\"$\202\323\344\223\002\036\"\031/v2/account/unl"
      "ink/google:\001*\022d\n\013UnlinkSteam\022\030.nakama.ap"
      "i.AccountSteam\032\026.google.protobuf.Empty\"#"
      "\202\323\344\223\002\035\"\030/v2/account/unlink/steam:\001*\022a\n\rU"
      "pdateAccount\022 .nakama.api.UpdateAccountR"
      "equest\032\026.google.protobuf.Empty\"\026\202\323\344\223\002\020\032\013"
      "/v2/account:\001*\022f\n\013UpdateGroup\022\036.nakama.a"
      "pi.UpdateGroupRequest\032\026.google.protobuf."
      "Empty\"\037\202\323\344\223\002\031\032\024/v2/group/{group_id}:\001*\022\224"
      "\001\n\026WriteLeaderboardRecord\022).nakama.api.W"
      "riteLeaderboardRecordRequest\032\035.nakama.ap"
      "i.LeaderboardRecord\"0\202\323\344\223\002*\" /v2/leaderb"
      "oard/{leaderboard_id}:\006record\022t\n\023WriteSt"
      "orageObjects\022&.nakama.api.WriteStorageOb"
      "jectsRequest\032\035.nakama.api.StorageObjectA"
      "cks\"\026\202\323\344\223\002\020\032\013/v2/storage:\001*\022\220\001\n\025WriteTou"
      "rnamentRecord\022(.nakama.api.WriteTourname"
      "ntRecordRequest\032\035.nakama.api.Leaderboard"
      "Record\".\202\323\344\223\002(\032\036/v2/tournament/{tourname"
      "nt_id}:\006recordB\205\003\n\031com.heroiclabs.nakama"
      ".apiB\rNakamaApiGrpcP\001Z\007apigrpc\242\002\004NKPB\252\002\006"
      "Nakama\222A\274\002\022u\n\rNakama API v2\"_\n!The Nakam"
      "a Authors & Contributors\022$https://github"
      ".com/heroiclabs/nakama\032\024hello@heroiclabs"
      ".com2\0032.0\032\016127.0.0.1:7350*\001\0012\020applicatio"
      "n/json:\020application/jsonZ\?\n\017\n\tBasicAuth\022"
      "\002\010\001\n\r\n\tBearerJwt\022\000\n\035\n\013HttpKeyAuth\022\016\010\002\032\010h"
      "ttp_key \002b\017\n\r\n\tBearerJwt\022\000r:\n\033Nakama ser"
      "ver documentation\022\033https://heroiclabs.co"
      "m/docsb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 8734);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "github.com/heroiclabs/nakama/apigrpc/apigrpc.proto", &protobuf_RegisterTypes);
  ::protobuf_annotations_2eproto::AddDescriptors();
  ::protobuf_google_2fprotobuf_2fempty_2eproto::AddDescriptors();
  ::protobuf_protoc_2dgen_2dswagger_2foptions_2fannotations_2eproto::AddDescriptors();
  ::protobuf_github_2ecom_2fheroiclabs_2fnakama_2dcommon_2fapi_2fapi_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto
namespace nakama {
namespace api {

// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace nakama
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif // #ifdef BUILD_GRPC_CLIENT
