name: 'Setup Vcpkg'
description: 'Clone and bootstrap vcpkg'
inputs:
  path:
    description: 'vcpkg repository path'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: microsoft/vcpkg
        path: vcpkg
    - run: "echo VCPKG_ROOT=${{ inputs.path }}} >> $GITHUB_ENV"
      shell: bash
    - if: runner.os == 'Linux'
      run: >
        sudo eatmydata "./bootstrap-vcpkg.sh"
      shell: bash
    - name: Setup NuGet API key
      shell: bash
      run: >
        $( type -p mono || :) `vcpkg fetch nuget | tail -n 1`
        setapikey "${{ secrets.GITHUB_TOKEN }}"
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
    - run: echo "VCPKG_BINARY_SOURCES=clear;nuget,GitHub,readwrite\n" >> $GITHUB_ENV
      shell: bash
    - name: 'Setup NuGet Credentials'
      shell: bash
      run: >
        mono=$( type -p mono || :);
        nuget="$mono $(vcpkg fetch nuget | tail -n 1)";
        $nuget sources list  | grep -q ${{ github.repository_owner }} || $nuget sources add
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        -storepasswordincleartext
        -name "GitHub"
        -username "heroiclabs"
        -password "${{ secrets.GITHUB_TOKEN }}"