name: Build Android
on: [workflow_call, workflow_dispatch]

jobs:
  build_android:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout nakama-cpp
        uses: actions/checkout@v4
        with:
          path: nakama-cpp
          submodules: false

      - name: Checkout vcpkg submodule
        run: |
          git submodule update --init --filter=blob:none -- submodules/vcpkg
        working-directory: nakama-cpp

      - uses: ./nakama-cpp/.github/actions/setup-android
        with:
          ndk-version: 27.2.12479018
          cmake-version: 4.0.2
      
      - uses: ./nakama-cpp/.github/actions/setup-vcpkg-android
        with:
          vcpkg-path: nakama-cpp/submodules/vcpkg

      - name : Build with Gradle
        run : ./gradlew build --no-daemon
        working-directory: nakama-cpp/android

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nakama-sdk-android-aar
          path: nakama-cpp/android/nakama-sdk/build/outputs/aar/*.aar
          if-no-files-found: error